### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mballaro** [ocean-data-challenges/2024_DC_SSH_mapping_SWOT_OSE#1]
- [ ] Add input on server
- [ ] Add method to download miost, 4dvarnet, 4dvarqg mapping solutions (v0.3 or v1.0)
- [ ] Update README
- [ ] Test it from scratch
- [ ] Make Realease + DOI
- [ ] Add Draft Article
- [ ] Add notebook qualitative assessment: SSH, current and vortocity fields
